ci:
  autoupdate_branch: devel
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.267
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.3
  hooks:
  - id: clang-format
    args:
    - '--style={BasedOnStyle: Google, SortIncludes: false}'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 23.10.0
  hooks:
  - id: black
