ci:
  autoupdate_branch: devel
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.8
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.6
  hooks:
  - id: clang-format
    args:
    - '--style={BasedOnStyle: Google, SortIncludes: false}'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
