ci:
  autoupdate_branch: devel
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.2
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.1
  hooks:
  - id: clang-format
    args:
    - '--style={BasedOnStyle: Google, SortIncludes: false}'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
  - id: black
